# Generated by Django 5.0.2 on 2024-02-22 15:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GivenId',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='VideoFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_file', models.CharField(max_length=100)),
                ('directory_name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Frame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x1', models.IntegerField()),
                ('y1', models.IntegerField()),
                ('width', models.IntegerField()),
                ('height', models.IntegerField()),
                ('original_image', models.CharField(max_length=100)),
                ('comment', models.TextField(blank=True, null=True)),
                ('given_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='frames', to='home.givenid')),
                ('video_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='frames', to='home.videofile')),
            ],
        ),
    ]
